// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Lb_DU0l9NQ61Xx2-1PqgQxg9y-AxPC8',
    appId: '1:450258900204:android:7a1d604a39d8df003001c9',
    messagingSenderId: '450258900204',
    projectId: 'fir-task-77690',
    storageBucket: 'fir-task-77690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFIE_TLQJrP9jcQ4jAne1zgVSJeohq-Ng',
    appId: '1:450258900204:ios:603663bc5ff7a5253001c9',
    messagingSenderId: '450258900204',
    projectId: 'fir-task-77690',
    storageBucket: 'fir-task-77690.appspot.com',
    androidClientId: '450258900204-d0avb0q08rlkpghc1uggda8jtiv5seq4.apps.googleusercontent.com',
    iosClientId: '450258900204-j7r4n5mipv0o53f1bnpl39kdipitbvl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.demotask',
  );
}
